### ISSUE TITLE
Help with Using it.

### ISSUE THREAD

**Issue by Squ4reHead** [ge1c4t/Automatic-Wabbajack#1]
As I dont know python and how it works I wasn't able to make it work. Is it possible to maybe make a guide or an exe version where I would use it like a program. I really want to use this but I can't.

**Comment by ge1c4t** [comment]
I'm working on an exe version, in the meantime, do you have python downloaded? https://www.python.org/downloads/release/python-394

**Comment by Squ4reHead** [comment]
Thats awessome to hear. Yes I have pyhton however because I've had problems downloading the installer I downloaded "Windows embeddable package" one and diddnt have any luck with it.

**Comment by gonaik** [comment]
thanks, exe\jar file will make it much better.
I managed to make the python program work, but it doesn't seem to be doing anything, it might be because the wabbajack changed how it is working, I see in your video you were clicking the manuall download then the slow download, but right now the wabbajack is automatically goes to the "slow download" directly, so that might be why it is not working anymore?

**Comment by alessfd** [comment]
I have no fucking idea how python works but managed to make the program show up by changing `import cv2 as cv` into `import autocv as cv`. Clicking the start button does absolutely nothing though.

**Comment by Squ4reHead** [comment]
Ive managed to install all theese : pyautogui , pysimplegui , opencv. and When I just simply run autowabbajack. The gui comes up but clicking the start button doesnt do anythin. Im i missing something ? I'd appriciate some help.

**Comment by gonaik** [comment]
well, I didn't have the patience for downloading all the mods manually so I just created some simple auto clicker for wabbajack in java, worked great for me for 2 modlists.
https://github.com/gonaik/AutoClickerWabbaJack

**Comment by gonaik** [comment]
well, I didn't have the patience for downloading all the mods manually so I just created some simple auto clicker for wabbajack in java, worked great for me for 2 modlists.
https://github.com/gonaik/AutoClickerWabbaJack

**Comment by ge1c4t** [comment]
https://github.com/ge1c4t/Wabbajack-Automagic
