### ISSUE TITLE
Tips on Making this work

### ISSUE THREAD

**Issue by hexeth** [ge1c4t/Automatic-Wabbajack#3]
## Installation 

1. Install python 3.8: https://www.python.org/downloads/
2. Open up command prompt and type `pip install pyautogui` then `pip install pysimplegui` and then `pip install opencv-python`
3. Download the release from here: https://github.com/ge1c4t/Automatic-Wabbajack/releases/
4. Run `autowabbajack.pyw` a purple little window should open
5. Hit `start`
6. Open Wabbajack and start the process.

## Tips

This application relies on looking at what's visible on your screen. With that in mind:

- The slow download button must be visible
- It seems to require being on the primary screen
- If you receive the error `Could not locate additional download button.` take a screenshot of the slow download button on your computer (crop it precisely) and overwrite `slow download.png` in the `img` folder. The computer vision seems to require a very precise match.
- This program will physically move your mouse and click the button, so don't expect to be able to use the computer during the process

Cheers,

**Comment by ge1c4t** [comment]
Added to readme, thank you 👍
